name: Release

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      upload-artifact:
        type: boolean
        default: true
        description: 'Upload artifacts'
      upload-tag:
        type: string
        default: "nightly"
        description: 'Upload tag'

jobs:
  build:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: ${{ inputs.upload-artifact || true }}
      upload-tag: ${{ inputs.upload-tag || (github.ref_type == 'tag' && github.ref_name || 'nightly') }}
    secrets: inherit