name: Release Build

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # 基础测试构建
  test-build:
    uses: ./.github/workflows/ci-multiplatform.yml

  # Flutter全平台构建
  release-build:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: ${{ github.ref_type == 'tag' && github.ref_name || 'nightly' }}
    secrets: inherit

  # 增强版Flutter构建 (如果需要更多控制)
  enhanced-build:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/flutter-build-enhanced.yml
    with:
      upload-artifact: true
      upload-tag: 'enhanced-${{ github.run_number }}'
    secrets: inherit